/** @type {import('tailwindcss').Config} */
export default {
  safelist: [
    "bg-amber-700",
    "bg-bjj-black",
    "bg-bjj-black/10",
    "bg-bjj-gray-200",
    "bg-bjj-gray-500",
    "bg-bjj-gray-700",
    "bg-bjj-red/60",
    "bg-bjj-red/80",
    "bg-bjj-white",
    "bg-bjj-white/30",
    "bg-bjj-white/80",
    "bg-bjj-belt-white",
    "bg-bjj-belt-blue",
    "bg-bjj-belt-purple",
    "bg-bjj-belt-brown",
    "bg-bjj-belt-black",
    "bg-bjj-belt-red",
    "bg-bjj-belt-red/80",
    "bg-bjj-belt-gray",
    "bg-bjj-belt-yellow",
    "bg-bjj-belt-orange",
    "bg-bjj-belt-green",
    "bg-bjj-belt-coral",
    "bg-bjj-belt-kids-yellow",
    "bg-bjj-belt-kids-orange",
    "bg-bjj-belt-kids-green",
    "bg-bjj-belt-kids-gray",
    "bg-blue-500",
    "bg-blue-600",
    "bg-gradient-to-r",
    "from-bjj-belt-red/80",
    "from-bjj-red/80",
    "to-bjj-belt-black/80",
    "to-bjj-black/80",
    "bg-gray-500",
    "bg-green-600",
    "bg-green-700",
    "bg-orange-500",
    "bg-purple-500",
    "bg-purple-600",
    "bg-white",
    "bg-yellow-500",
    "bg-zinc-400",
    "text-bjj-black",
    "text-bjj-black/80",
    "text-bjj-white",
    "text-bjj-white/80",
  ],
  theme: {
    extend: {
      // Global DaisyUI themes (zdark/zlight) live in styles/tailwind.css via @plugin "daisyui/theme".
      // These bjj-* tokens are belt-only colors and must not override base/primary/etc.
      colors: {
        'bjj-black': '#000000',
        'bjj-white': '#ffffff',
        'bjj-gray-50': '#f7f7f7',
        'bjj-gray-100': '#f3f4f6',
        'bjj-gray-200': '#d9d9d9',
        'bjj-gray-300': '#c7c7c7',
        'bjj-gray-400': '#9e9e9e',
        'bjj-gray-500': '#6b6b6b',
        'bjj-gray-600': '#545454',
        'bjj-gray-700': '#3a3a3a',
        'bjj-gray-800': '#2e2e2e',
        'bjj-gray-900': '#1a1a1a',
        'bjj-gray-925': '#141414',
        'bjj-gray-950': '#0b0b0b',
        'bjj-red': '#e10600',
        // Belt base tokens (used via src/tokens/bjjBeltTokens.ts).
        'bjj-belt-white': '#ffffff',
        'bjj-belt-blue': '#2563eb',
        'bjj-belt-purple': '#7c3aed',
        'bjj-belt-brown': '#b45309',
        'bjj-belt-black': '#000000',
        'bjj-belt-red': '#e10600',
        'bjj-belt-coral': '#d64045',
        'bjj-belt-gray': '#6b7280',
        'bjj-belt-yellow': '#eab308',
        'bjj-belt-orange': '#f97316',
        'bjj-belt-green': '#15803d',
        'bjj-belt-kids-yellow': '#eab308',
        'bjj-belt-kids-orange': '#f97316',
        'bjj-belt-kids-green': '#15803d',
        'bjj-belt-kids-gray': '#6b7280',
      },
    },
  },
};
